### ISSUE TITLE
预训练模型与数据集的配对问题

### ISSUE THREAD

**Issue by codgodtao** [liangjiandeng/PanCollection#1]
Dear Professor,

I have a question regarding the dataset used in your paper "Machine Learning in Pansharpening: A Benchmark, From Shallow to Deep Networks". I noticed that the dataset used in the paper does not seem to be consistent with pancollection. In addition, pre-trained models for all methods on four satellites were provided in the 01-DL toolbox (pytorch)，I would like to know if these pre-trained models were trained on pancollection. This information will help me determine whether I need to retrain these models for a fair comparison. Thank you in advance for taking the time to answer my question.

Best regards

**Comment by liangjiandeng** [comment]
Thanks for your question.
        Due to the copyright issue, we did not share the dataset used in the GRSM paper, thus the pretrained models in toolbox are specifically for the GRSM work. To use the toolbox without copyright issue, we simulated a new collection thus released the pancollection dataset. Therefore, you need to retrain the methods in the toolbox by the pancollection dataset.The following Chinese paper is associated with the pancollection dataset, you may refer to its results.本刊体例 (liangjiandeng.github.io)Best,Liangjian
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年6月3日 17:11
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [liangjiandeng/PanCollection] 预训练模型与数据集的配对问题 (Issue #1)
        
      
    
  

Dear Professor,
I have a question regarding the dataset used in your paper "Machine Learning in Pansharpening: A Benchmark, From Shallow to Deep Networks". I noticed that the dataset used in the paper does not seem to be consistent with pancollection. In addition, pre-trained models for all methods on four satellites were provided in the 01-DL toolbox (pytorch)，I would like to know if these pre-trained models were trained on pancollection. This information will help me determine whether I need to retrain these models for a fair comparison. Thank you in advance for taking the time to answer my question.
Best regards

**Comment by codgodtao** [comment]
T

**Comment by codgodtao** [comment]
Thank you very much! This will help me a lot
